export const languageExtensions: { [key: string]: string[] } = {
  json: [".json", ".jsonc"],
  javascript: [".js", ".jsx", ".mjs", ".cjs"],
  typescript: [".ts", ".tsx"],
  python: [".py", ".pyw", ".pyc", ".pyd", ".pyo", ".pyz"],
  java: [".java", ".jav"],
  c: [".c", ".h"],
  cpp: [".cpp", ".cxx", ".cc", ".h", ".hpp", ".hxx"],
  csharp: [".cs"],
  go: [".go"],
  ruby: [".rb", ".ruby"],
  php: [".php", ".php4", ".php5", ".phps", ".phtml"],
  perl: [".pl", ".pm"],
  rust: [".rs"],
  swift: [".swift"],
  kotlin: [".kt", ".kts"],
  scala: [".scala", ".sc"],
  sql: [".sql"],
  html: [".html", ".htm"],
  css: [".css"],
  sass: [".sass", ".scss"],
  markdown: [
    ".md",
    ".markdown",
    ".mdx",
    ".mdown",
    ".mkd",
    ".mkdn",
    ".mdwn",
    ".mdtxt",
    ".mdtext",
    ".text",
  ],
  yaml: [".yaml", ".yml"],
  xml: [".xml", ".xsl", ".xsd", ".svg"],
  dockerfile: [".dockerfile"],
  bash: [".sh", ".bash"],
  powershell: [".ps1", ".psm1", ".psd1"],
  batch: [".bat", ".cmd"],
  r: [".r", ".R"],
  matlab: [".m"],
  lua: [".lua"],
  clojure: [".clj", ".cljs", ".cljc"],
  groovy: [".groovy", ".gvy", ".gy", ".gsh"],
  elixir: [".ex", ".exs"],
  erlang: [".erl", ".hrl"],
  haskell: [".hs", ".lhs"],
  ocaml: [".ml", ".mli"],
  fsharp: [".fs", ".fsi", ".fsx", ".fsscript"],
  dart: [".dart"],
  pascal: [".pas", ".p", ".pp"],
  fortran: [".f", ".f90", ".f95", ".f03", ".for", ".ftn"],
  assembly: [".asm", ".s"],
  objectivec: [".m", ".mm"],
  shell: [".sh", ".bash", ".zsh", ".csh", ".tcsh"],
  vbscript: [".vbs"],
  delphi: [".dpr", ".dfm", ".pas"],
  julia: [".jl"],
  prolog: [".pl", ".pro"],
  coffeescript: [".coffee"],
  actionscript: [".as"],
  smalltalk: [".st"],
  lisp: [".lisp", ".lsp"],
  scheme: [".scm", ".ss"],
  hack: [".hh", ".php"],
};
