export const languageExtensions: { [key: string]: string[] } = {
  json: [".json", ".jsonc"],
  javascript: [".js", ".jsx", ".mjs", ".cjs"],
  typescript: [".ts", ".tsx"],
  python: [
    ".py",
    ".pyw",
    ".pyc",
    ".pyd",
    ".pyo",
    ".pyz",
    ".pynb",
    ".ipy",
    ".pyi",
    ".pyx",
    ".pxd",
    ".pxi",
  ],
  java: [".java", ".jav", ".class", ".jar", ".jmod"],
  c: [".c", ".h", ".i", ".ii"],
  cpp: [
    ".cpp",
    ".cxx",
    ".cc",
    ".h",
    ".hpp",
    ".hxx",
    ".hh",
    ".h++",
    ".c++",
    ".tcc",
    ".inl",
  ],
  csharp: [".cs", ".csx", ".cake"],
  go: [".go"],
  ruby: [".rb", ".ruby", ".rbw", ".rake", ".gemspec", ".podspec", ".jbuilder"],
  php: [".php", ".php4", ".php5", ".phps", ".phtml", ".phar"],
  perl: [".pl", ".pm", ".t", ".pod", ".psgi"],
  rust: [".rs", ".rlib", ".toml"],
  swift: [".swift"],
  kotlin: [".kt", ".kts", ".ktm"],
  scala: [".scala", ".sc"],
  sql: [
    ".sql",
    ".ddl",
    ".dml",
    ".tpl",
    ".prc",
    ".fnc",
    ".pks",
    ".pkb",
    ".snippets",
  ],
  html: [".html", ".htm", ".xhtml"],
  css: [".css"],
  sass: [".sass", ".scss"],
  markdown: [
    ".md",
    ".markdown",
    ".mdx",
    ".mdown",
    ".mkd",
    ".mkdn",
    ".mdwn",
    ".mdtxt",
    ".mdtext",
    ".text",
    ".mdown",
    ".markdn",
    ".mkdown",
  ],
  yaml: [".yaml", ".yml"],
  xml: [".xml", ".xsl", ".xsd", ".svg", ".rss", ".wsdl", ".xslt", ".plist"],
  dockerfile: [".dockerfile", ".Dockerfile"],
  bash: [".sh", ".bash", ".zsh", ".csh", ".tcsh", ".ksh", ".bats", ".command"],
  powershell: [".ps1", ".psm1", ".psd1"],
  batch: [".bat", ".cmd"],
  r: [".r", ".R", ".Rhistory", ".Rprofile", ".RData", ".Rproj"],
  matlab: [".m", ".mat", ".mlx"],
  lua: [".lua"],
  clojure: [".clj", ".cljs", ".cljc", ".edn"],
  groovy: [".groovy", ".gvy", ".gy", ".gsh"],
  elixir: [".ex", ".exs"],
  erlang: [".erl", ".hrl"],
  haskell: [".hs", ".lhs", ".hsc"],
  ocaml: [".ml", ".mli", ".mll", ".mly"],
  fsharp: [".fs", ".fsi", ".fsx", ".fsscript"],
  dart: [".dart"],
  pascal: [".pas", ".p", ".pp", ".inc", ".lpr", ".dpr"],
  fortran: [".f", ".f90", ".f95", ".f03", ".for", ".ftn", ".f77", ".f08"],
  assembly: [".asm", ".s", ".S", ".inc"],
  objectivec: [".m", ".mm", ".h"],
  shell: [".sh", ".bash", ".zsh", ".csh", ".tcsh", ".ksh", ".bats", ".command"],
  vbscript: [".vbs", ".vbe", ".wsf", ".wsc"],
  delphi: [
    ".dpr",
    ".dfm",
    ".pas",
    ".dpk",
    ".dproj",
    ".groupproj",
    ".bdsgroup",
    ".bdsproj",
  ],
  julia: [".jl"],
  prolog: [".pl", ".pro", ".P", ".lgt", ".yap"],
  coffeescript: [".coffee", ".litcoffee", ".coffee.md"],
  actionscript: [".as"],
  smalltalk: [".st", ".cs"],
  lisp: [".lisp", ".lsp", ".cl", ".fasl"],
  scheme: [".scm", ".ss", ".sld", ".sls", ".sps", ".spt"],
  hack: [".hh", ".php"],
  jupyter: [".ipynb"],
};
